server:
  port: 8091

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/myblog


my-mongo-config:
  mongo-url: mongodb://localhost:27017
  mongo-db: blogposts